title: Bird Docs
description: Documentation for Bird
url: "https://atinder.github.io"
baseurl: "/bird-docs"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:path/
    source: docs

# Default front matter
defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github 