title: Bird Docs
description: Documentation for Bird
url: "https://atinder.github.io"
# baseurl is set via command line for PR previews

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github 