name: Cleanup PR Previews

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Remove PR Preview
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_DIR="preview/pr-${PR_NUMBER}"
          
          # Configure git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Remove preview directory
          if [ -d "$PREVIEW_DIR" ]; then
            rm -rf "$PREVIEW_DIR"
            git add -A
            git commit -m "Remove preview for PR #${PR_NUMBER}" || echo "No changes to commit"
            git push origin gh-pages
          fi 