name: Sync Docs to Crisp

on:
  push:
    branches:
      - master

jobs:
  sync-crisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: Install dependencies
        run: gem install dotenv

      - name: Sync to Crisp
        run: bundle exec ruby _scripts/sync_to_crisp.rb
        env:
          CRISP_IDENTIFIER: ${{ secrets.CRISP_IDENTIFIER }}
          CRISP_KEY: ${{ secrets.CRISP_KEY }}
          CRISP_WEBSITE_ID: ${{ secrets.CRISP_WEBSITE_ID }}
