name: Preview Docs

on:
  pull_request:
    branches: [ "master", "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

# Allow concurrent deployments for different PRs
concurrency:
  group: "pages-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.3'
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Building site for PR #${PR_NUMBER}"
          bundle exec jekyll build --config _config.yml --baseurl "/bird-docs/pr-${PR_NUMBER}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: pr-preview-${{ github.event.pull_request.number }}
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
          artifact_name: pr-preview-${{ github.event.pull_request.number }}

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const prNumber = context.issue.number;
            const previewUrl = `https://${owner}.github.io/${repo}/pr-${prNumber}/`;
            
            github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              body: `📚 Documentation preview is ready!\nYou can view it here: ${previewUrl}\n\nThis preview will be updated automatically when you push new changes to the PR.`
            }); 